# The Default Profile
[profile.default]
solc_version = '0.8.20'
auto_detect_solc = false
optimizer = true
optimizer_runs = 200
fuzz_runs = 10

remappings = [
    "ds-test/=lib/solmate/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-upgradeable-contracts/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

# Extreme Fuzzing CI Profile :P
[profile.ci]
solc_version = '0.8.20'
# 100_000
fuzz_runs = 100_000

# RPC Endpoints
[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
arbitrum = { key = "${ETHERSCAN_KEY}" }