name: ci

on: [push]

env:
  ALCHEMY_API_KEY: ${{secrets.ALCHEMY_API_KEY}}

jobs:
  tests:
    name: Forge Testing
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install
      
      - name: Run Forge build
        run: FOUNDRY_PROFILE=ci forge build --sizes

      - name: Run Tests
        run: FOUNDRY_PROFILE=ci forge test